# Generated by Django 3.2.7 on 2021-11-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined_semester', max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Semseter',
        ),
        migrations.AddField(
            model_name='mark',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
    ]
